### ISSUE TITLE
Android readable links

### ISSUE THREAD

**Issue by bernardovalente** [berkansezer77/home-assistant#1]
Hi, 

Great work on this writing, it's a good way to feed information to HA.
Do you know if there's there any way to open and read links within HA without opening the browser? You noted that it was an IOS function.

Thank you

**Comment by berkansezer77** [comment]
Hi. Thank you very much for your kind words. I am afraid I do not know any other way on android. Opening links is a basic function of ha. I have to try and test it but I do not own any android device for now.
