### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by n4tur3502** [berkansezer77/home-assistant#2]
I have followed your steps and gotten this mostly working but I am running into a couple issues. First, I have no player controls when I start something. I can see whats playing and select the media players I want but no way to stop/pause or skip. Second, I have an error in the card about Entity not available: switch.switch_bedroom. Not quite sure what to do with that. Otherwise this is absolutely fantastic and any help would be greatly appreciated.

**Comment by berkansezer77** [comment]
Hellow. Thank you very much for your nice words. 

I have some difficulties in undestanding your actual problem. 

"I have no player controls" 

I used mushroom media player in the page and when you enter spotify entity it should come up with all the necessary media control buttons. Please check mushroom media player page. 

about switch.switch.bedroom: The entity here has no function. The important thing here is to place an proper image. The entity is asked and must be filled for picture entity to function properly. Bu as I said it is just a need to fill an enttity name but has no function at all. Just place correct image name.
