### ISSUE TITLE
Colored pics

### ISSUE THREAD

**Issue by cob94440** [berkansezer77/home-assistant#3]
hello Nice work. I managed to put my stuff inside and it works fine.
Two things left i guess.
Where or how did you find the colorized room pics.
And second you have lots of scene for the lights but i do not find them 
thanks in advance

**Comment by cob94440** [comment]
Also Next to calendar card there is camera cards.
Whats is input_boolean.ana_sayfa_kamera_ev for please

**Comment by cob94440** [comment]
And what is                                         binary_sensor.salon_cam_sensor_cb529e23_ias_zone
please

**Comment by berkansezer77** [comment]
It is my window sensor. It detects whether the window is open or closed.

**Comment by berkansezer77** [comment]
> hello Nice work. I managed to put my stuff inside and it works fine. Two things left i guess. Where or how did you find the colorized room pics. And second you have lots of scene for the lights but i do not find them thanks in advance

Use prisma app for on ios or google play for colorized pictures. Just take a shot of your rooms and edit them in prisma then put them into your HA folder. 
Scenes are located under boolean.scenes. I have multiple scenes for multiple rooms.
