### ISSUE TITLE
Some dead links

### ISSUE THREAD

**Issue by Krispkiwi** [berkansezer77/home-assistant#4]
Hey, just letting you know there's a few dead links on the page:

https://github.com/berkansezer77/home-assistant/blob/main/pages/spotify-card-v2/force-spotify-to-update-status
https://github.com/berkansezer77/home-assistant/blob/main/pages/spotify-card-v2/last-room-motion

**Comment by berkansezer77** [comment]
A new version of Spotify card has been released. So all the files are now replaced with the new ones.
