### ISSUE TITLE
Weather card.

### ISSUE THREAD

**Issue by cob94440** [berkansezer77/home-assistant#6]
Hello. I have a problem with template sensor.

`{{ (states.weather.forecast_home_hourly.attributes.forecast[0].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[1].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[2].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[3].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[4].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[5].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[6].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[7].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[8].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[9].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[10].precipitation|float +
      states.weather.forecast_home_hourly.attributes.forecast[11].precipitation|float)|round(1) }}`

It gives me :'None' has no attribute 'attributes'

**Comment by berkansezer77** [comment]
Have you installed met.no integration ?

**Comment by cob94440** [comment]
Yes 

![image](https://github.com/berkansezer77/home-assistant/assets/62489067/bf773376-0a70-400a-8fdc-125963d1936a)
![image](https://github.com/berkansezer77/home-assistant/assets/62489067/06945cf7-5c23-45b6-97de-dc3baa3accb2)

**Comment by cob94440** [comment]
I don't have hourly forecast for met.no.

Maybe i have to make a template sensor like this:


`template:
  - trigger:
      - platform: time_pattern
        hours: /1
    action:
      - service: weather.get_forecast
        data:
          type: hourly
        target:
          entity_id: weather.home
        response_variable: hourly
    sensor:
      - name: Weather Forecast Hourly
        unique_id: weather_forecast_hourly
        state: "{{ now().isoformat() }}"
        attributes:
          forecast: "{{ hourly.forecast }}"`

**Comment by berkansezer77** [comment]
It is propably unavailable. Go to your integrations page. Click on met.no then click on 2 entities, you will see that it is unavailable. Just enable it.

![image](https://github.com/berkansezer77/home-assistant/assets/84282504/a3d80d2d-df49-4678-9f30-8cff48ee385d)

**Comment by cob94440** [comment]
No only 1 entry 
![image](https://github.com/berkansezer77/home-assistant/assets/62489067/c0b806db-a485-4b67-a771-59698c5a7a0a)

I'm on latest HA

**Comment by berkansezer77** [comment]
I haven't done any template sensor. It was already there from the begining but only was shown as disabled at the begining. Try to uninstall then reinstall met.no.

**Comment by berkansezer77** [comment]
Co did you sort it out ? Can I close it ?

**Comment by cob94440** [comment]
Yes it's ok now. I hadn't those options. i end up using another weather integration
