### ISSUE TITLE
Problem with placement

### ISSUE THREAD

**Issue by Jonny-T-cyber** [berkansezer77/home-assistant#8]
Hello!
There is a problem with the number positioning, as you can see in the following screenshot:

![image](https://github.com/berkansezer77/home-assistant/assets/33354144/90dbd324-d6fa-41e7-9343-1f521f2b4165)

How can I fix it?
Thanks

**Comment by berkansezer77** [comment]
Mushroom V3.4.0 has been redesigned to fit with tile cards and unfortunately this caused some issues in card mode. I have updated the code and everything should work fine now.

**Comment by berkansezer77** [comment]
Can you try using theme mushroom shadow ? 

![image](https://github.com/berkansezer77/home-assistant/assets/84282504/477b4690-62bf-4a5d-baa0-32645b2848fc)
